config/routes.rb
Rails.application.routes.draw do
  get '/all', :to => 'people#all', :as => :all_people
  resources :people
  root 'people#index'

end

app/models/person.rb
class Person < ActiveRecord::Base
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :first_name, length: { minimum: 3 }
  validates :last_name, length: { minimum: 3 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = Person.all
  end
  
  def new
    @person = Person.new
  end
  
  def create
    @person = Person.create(person_params)
    if @person.save
      flash[:success] = "You created a new person!"
      redirect_to @person
    else
      flash[:error] = "There was an error when creating the new person."
      render :new
    end
  end
  
  def show
    @person = Person.find(params[:id])
  end
  
  def all
    @people = Person.all
  end
  
  private
    def person_params
      params.require(:person).permit(:first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NameDisplay</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Person', root_path, class: 'navbar-brand'%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'All People', all_people_path %></li>
      </ul>
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="container">
  <div class="col-md-6 col-md-offset-3">
    <% flash.each do |name, message| %>
      <%= content_tag :div, message, class: name %>
    <% end %>
  </div>
</div>

<div class="container">
  <%= yield %>
</div>



</body>
</html>

app/views/people/all.html.erb
<% @people.each do |person|%>
  <p>Name: <%= person.first_name %> <%= person.last_name %></p>
<% end %>

app/views/people/index.html.erb
<h2>People</h2>
<p>Add a new name: <%= link_to 'New Person', new_person_path %></p>

app/views/people/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="well">
      
      <% if @person.errors.any? %>
        <div id="error_explanation">
          <ul>
          <% @person.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <h2>New Person</h2>

      <%= form_for @person, url: {action: "create"} do |p| %>
        
        <div class="form-group">
        <%= p.label :first_name %>
        <%= p.text_field :first_name, class: 'form-control' %>
        </div>
        
        <div class="form-group">
        <%= p.label :last_name %>
        <%= p.text_field :last_name, class: 'form-control' %>
        </div>
        
        <div class="form-group">
        <%= p.submit "Create Person", class: 'btn btn-success' %>
        </div>
        
      <% end %>
    </div>
  </div>
</div>

app/views/people/show.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h4>Person number: <%= @person.id %></h4>
    <p>First Name: <%= @person.first_name %></p>
    <p>Last Name: <%= @person.last_name %></p>
  </div>
</div>